<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>$_GET, $_POST & $_REQUEST</title>
</head>
<body>
    <!-- <form action="testform.php" method="get"> -->
    <form action="testform.php" method="post">
        Name: <input type="text" name="fname"><br><br>
        Age: <input type="text" name="age"><br><br>
        <input type="submit" name="save">
    </form>
</body>
</html>